project:
  type: website
  output-dir: docs
  resources:
    - encuentros/1-intro-r/intro-r.scss

website:
  #logo: jsm-logo.png
  #repo-url: https://github.com/pablotis/intro-r-quarto/settings/pages
  #repo-actions: [edit, issue]
  back-to-top-navigation: true
  navbar:
    logo: "img/Logo_PNG_Baja_Mesa de trabajo 1.png"
    search: true
    left:
      - href: index.qmd
        text: "Inicio"
      - href: programa.qmd
        text: "Programa"
      - href: encuentros/0-puesta-a-punto/index.qmd
        text: "Puesta a punto"
      - href: profesor.qmd
        text: "Docente"
      - text: "Encuentros"
        menu:
          - text: "Clase 0: Puesta a punto"
            href: encuentros/0-puesta-a-punto/index.qmd
          - text: "Módulo 1: Intro al curso y EPH"
            href: encuentros/1-intro-curso-eph/index.qmd
          # --- ENCUENTROS BLOQUEADOS (sin href) ---
          - text: "Módulo 2: Intro a R + IA (próximamente)"
          - text: "Módulo 3: tidyverse I (próximamente)"
          - text: "Módulo 4: tidyverse II (próximamente)"
          - text: "Módulo 5: Proyectos y organización (próximamente)"
          - text: "Módulo 6: ggplot2 + TP integrador (próximamente)"
      - text: "Ejercitación"
        menu:
         # --- EJERCITACIONES BLOQUEADAS (sin href) ---
         - text: "Módulo 2: Intro a R (próximamente)"
         - text: "Módulo 3: tidyverse I (próximamente)"
         - text: "Módulo 4: tidyverse II (próximamente)"
         - text: "Módulo 5: Proyectos (próximamente)"
         - text: "Módulo 6: ggplot2 (próximamente)"
    right: 
      - href: cod_de_conducta.qmd
        text: Código de conducta
    # tools:
    #   - icon: github
    #     href: https://github.com/Estacion-R/intro-r-quarto
 
format:
  html:
    theme: cosmo
    toc: true

editor: visual

execute:
  freeze: auto
